apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 2  # You can change this to the number of pods you want
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: abhi9604/my-node-app:latest  # Replace with your image, e.g. abhishekdhaiskar/nodejs-app:latest
        ports:
        - containerPort: 3000
