apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer  # Or NodePort if you are on local or don’t want cloud LB
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 3000  # Container port
